// Ghost Performance Remotion schema — Phase 2 architecture (stub).
//
// When rendering Ghost Performance videos with Remotion, these props define
// the full data contract for the composition. The visualizer components receive
// currentFrame and fps instead of a live AnalyserNode, and audio is provided
// as pre-analysed data arrays.

import type { GhostPerformanceMeta, GhostInstrument } from '@/lib/types'

export interface PreAnalysedFrame {
  // Per-frame frequency magnitude data (Uint8Array serialised as number[])
  frequencies: number[]
  // Per-frame waveform data (Float32Array serialised as number[])
  waveform: number[]
  // Computed bands for convenience
  bass: number; lowMid: number; mid: number
  highMid: number; high: number; presence: number
  overall: number; transient: boolean; peak: number
}

export interface GhostPerformanceVideoProps {
  // Song metadata
  trackTitle:    string
  trackSlug:     string
  albumTitle:    string
  audioPath:     string   // path relative to Remotion static folder

  // Visual
  coverImagePath?:   string
  songArtPath?:      string
  chapterEmotion?:   string

  // Ghost Performance config
  ghostMeta:    GhostPerformanceMeta

  // Pre-analysed audio data (one entry per frame at the composition FPS)
  // Generated by the offline audio analysis pipeline (scripts/analyse-audio.ts)
  analysedFrames: PreAnalysedFrame[]

  // Optional MIDI note events (Phase 2)
  midiNotes?: Array<{
    midi: number; time: number; duration: number; velocity: number; channel: number
  }>

  // Composition settings
  fps:          number   // typically 30
  durationSec:  number

  // Intro/outro
  showIntro:    boolean
  showOutro:    boolean
  introSec:     number   // duration of intro overlay
  outroSec:     number
}

// Default props for Remotion Studio preview
export const GHOST_PERFORMANCE_DEFAULT_PROPS: GhostPerformanceVideoProps = {
  trackTitle:    'Ghost Performance Preview',
  trackSlug:     'preview',
  albumTitle:    'NoiraCiel',
  audioPath:     'audio/preview.mp3',
  chapterEmotion: 'The invisible band performing.',
  ghostMeta: {
    enabled:           true,
    mode:              'auto',
    primaryInstrument: 'energy',
    visualStyle:       'noir-cinematic',
    accentColor:       'blue-gold',
    showInstrument:    true,
    showParticles:     true,
    showWaveform:      false,
  },
  analysedFrames: [],
  fps:            30,
  durationSec:    180,
  showIntro:      true,
  showOutro:      true,
  introSec:       3,
  outroSec:       4,
}
